# Generated by Django 6.0.1 on 2026-05-11 07:12

import django.db.models.deletion
import worlds.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="World",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("genre", models.CharField(blank=True, max_length=160)),
                ("aesthetic_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worlds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorldCoverImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, upload_to=worlds.models.world_cover_upload_path
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("generated", "Generated"), ("uploaded", "Uploaded")],
                        default="generated",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField(blank=True)),
                ("model_id", models.CharField(default="gpt-image-2", max_length=80)),
                ("error_message", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
                ("generation_task_id", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cover_images",
                        to="worlds.world",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="world",
            index=models.Index(
                fields=["owner", "-updated_at"], name="worlds_worl_owner_i_83a6d0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="world",
            constraint=models.UniqueConstraint(
                fields=("owner", "slug"), name="unique_world_slug_per_owner"
            ),
        ),
        migrations.AddIndex(
            model_name="worldcoverimage",
            index=models.Index(
                fields=["world", "-created_at"], name="worlds_worl_world_i_f8735e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="worldcoverimage",
            index=models.Index(fields=["status"], name="worlds_worl_status_47b18d_idx"),
        ),
        migrations.AddConstraint(
            model_name="worldcoverimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("world",),
                name="unique_active_cover_per_world",
            ),
        ),
    ]
