# Generated by Django 6.0.1 on 2026-05-12 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_tasks", "0001_initial"),
        ("worlds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="worldcoverimage",
            name="ai_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cover_images",
                to="ai_tasks.aitask",
            ),
        ),
        migrations.AddIndex(
            model_name="worldcoverimage",
            index=models.Index(
                fields=["ai_task"], name="worlds_worl_ai_task_4a17a9_idx"
            ),
        ),
    ]
