# Generated by Django 6.0.1 on 2026-05-12 04:18

import django.db.models.deletion
import world_artifacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("worlds", "0002_worldcoverimage_ai_task_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportantEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("time_period", models.CharField(blank=True, max_length=160)),
                (
                    "event_state",
                    models.CharField(
                        choices=[
                            ("historical", "Historical"),
                            ("current", "Current"),
                            ("predicted", "Predicted"),
                            ("mythic", "Mythic"),
                            ("disputed", "Disputed"),
                        ],
                        default="historical",
                        max_length=20,
                    ),
                ),
                ("participants", models.TextField(blank=True)),
                ("causes", models.TextField(blank=True)),
                ("consequences", models.TextField(blank=True)),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="worlds.world",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["world", "title"], name="world_artif_world_i_c56057_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoryConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seed", models.TextField(blank=True)),
                ("premise", models.TextField(blank=True)),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="worlds.world",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["world", "title"], name="world_artif_world_i_640c35_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorldCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(blank=True, max_length=160)),
                ("appearance", models.TextField(blank=True)),
                ("personality", models.TextField(blank=True)),
                ("motivations", models.TextField(blank=True)),
                ("current_status", models.CharField(blank=True, max_length=160)),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="worlds.world",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["world", "title"], name="world_artif_world_i_5eb0bf_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorldImageReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.FileField(
                        blank=True,
                        upload_to=world_artifacts.models.reference_image_upload_path,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("generated", "Generated"), ("uploaded", "Uploaded")],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("inspiration", "Inspiration"),
                            ("literal", "Literal"),
                            ("concept", "Concept"),
                        ],
                        default="inspiration",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="worlds.world",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["world", "title"], name="world_artif_world_i_28d0bd_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorldLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("location_type", models.CharField(blank=True, max_length=120)),
                ("geography", models.TextField(blank=True)),
                ("visual_character", models.TextField(blank=True)),
                ("significance", models.TextField(blank=True)),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="worlds.world",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["world", "title"], name="world_artif_world_i_002dab_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WorldTruth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="worlds.world",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["world", "title"], name="world_artif_world_i_c22ee4_idx"
                    )
                ],
            },
        ),
    ]
