# Generated by Django 6.0.1 on 2026-05-12 04:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("worlds", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIWorkerHeartbeat",
            fields=[
                (
                    "worker_id",
                    models.CharField(max_length=160, primary_key=True, serialize=False),
                ),
                ("queues", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["worker_id"],
            },
        ),
        migrations.CreateModel(
            name="AITask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("world_cover_generation", "World cover generation")],
                        max_length=80,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("dead_lettered", "Dead lettered"),
                        ],
                        default="queued",
                        max_length=24,
                    ),
                ),
                ("target_object_id", models.CharField(blank=True, max_length=64)),
                ("input_payload", models.JSONField(blank=True, default=dict)),
                ("result_payload", models.JSONField(blank=True, default=dict)),
                (
                    "provider",
                    models.CharField(blank=True, default="openai", max_length=80),
                ),
                ("provider_model", models.CharField(blank=True, max_length=120)),
                ("provider_request_id", models.CharField(blank=True, max_length=200)),
                ("queue_job_id", models.CharField(blank=True, max_length=200)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=1)),
                ("retry_not_before", models.DateTimeField(blank=True, null=True)),
                ("lease_owner", models.CharField(blank=True, max_length=160)),
                ("leased_at", models.DateTimeField(blank=True, null=True)),
                ("provider_started_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("last_failed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "world",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tasks",
                        to="worlds.world",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AITaskEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField()),
                ("event_type", models.CharField(max_length=80)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="ai_tasks.aitask",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="aitask",
            index=models.Index(
                fields=["owner", "status"], name="ai_tasks_ai_owner_i_3476c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aitask",
            index=models.Index(
                fields=["world", "status"], name="ai_tasks_ai_world_i_ff5bc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aitask",
            index=models.Index(
                fields=["kind", "status"], name="ai_tasks_ai_kind_cc3012_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aitask",
            index=models.Index(
                fields=["status", "retry_not_before"],
                name="ai_tasks_ai_status_d8622a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aitask",
            index=models.Index(
                fields=["status", "leased_at"], name="ai_tasks_ai_status_5bc152_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aitask",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="ai_tasks_ai_target__d349c5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="aitaskevent",
            constraint=models.UniqueConstraint(
                fields=("task", "sequence"), name="unique_ai_task_event_sequence"
            ),
        ),
    ]
